###########################################################################
#  Author : MANU P ANAND : email:manupanand@outlook.com
############################################################################
# sudo kubeadm reset # uninstall all and reset control plane if error
#"PS1="MASTER->"
#crictl ps #similar to docker ps for containerd
######################################################################################################

# including common task
- name: Including common task 
  ansible.builtin.include_role:  
    name: common 
    tasks_from: common


- name: Enable ports using firewalld
  ansible.builtin.shell: "firewall-cmd --zone=trusted --add-port={{ item }}/tcp --permanent && firewall-cmd --reload"
  loop: 
    - 22 # ssh 
    - 443 #https
    - 6443 #kubeapiserver
    - 10250    # kubelet
    - 10259 #kube-scheduler
    - 10257 #kube-control-manger
- name: Enable port range - 2379-2380 etcd
  ansible.builtin.shell: "firewall-cmd --zone=trusted --add-port=2379-2380/tcp --permanent && firewall-cmd --reload"
      
#############################################################
# disable swap |disk partition
# swapoff -a #disable al swap area
# use rhel ot ubuntu
# sudo swapoff -a  # check commands
# # sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
##############################################################


######################### Only for control plane ###############################  
- name: Install K9s 
  ansible.builtin.unarchive: 
   src: https://github.com/derailed/k9s/releases/download/v0.40.10/k9s_Linux_amd64.tar.gz
   dest: "/usr/local/bin/"
   mode: '0744'
   remote_src: true
  

- name: Get IP address 
  ansible.builtin.shell:  hostname -I | awk '{print $1}' 
  register: ip_address


- name: Debug 
  ansible.builtin.debug: 
     msg: "{{ ip_address.stdout }}"

- name: Generate master node token 
  ansible.builtin.shell: "kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={{  ip_address.stdout }} --node-name master"
  register: token 

- name: Copy token to a file 
  ansible.builtin.copy: 
    content: "{{ token.stdout }}"
    dest: "/tmp/token.sh"
    mode: '0660'
  

- name: Run kube configuration
  ansible.builtin.shell: | 
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config 

- name: Install Calico 
  ansible.builtin.shell: |
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/tigera-operator.yaml 
    curl https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/custom-resources.yaml -O 
    kubectl create -f custom-resources.yaml
    
- name: generate join token again 
  ansible.builtin.shell:  "kubeadm token create --print-join-command"
  register: join_command

- name: Copy join command 
  ansible.builtin.copy: 
   content: "{{ join_command.stdout }}"
   dest: "/tmp/join.sh"
   mode: '0660'
    

